#include <unistd.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_std.h"
#include "common.h"

#ifdef USE_BADGE_BSP
#include "bsp/audio.h"
#endif

static i2s_chan_handle_t                tx_chan;        // I2S tx channel handler
void mixer_callback (void *opaque, uint8_t *stream, int free);

static void i2s_task(void *arg)
{
	int16_t buf[128];
	int core_id = esp_cpu_get_core_id();
	fprintf(stderr, "i2s runs on core %d\n", core_id);

	xEventGroupWaitBits(global_event_group,
			    BIT0,
			    pdFALSE,
			    pdFALSE,
			    portMAX_DELAY);

	i2s_channel_enable(tx_chan);
	for (;;) {
		size_t bwritten;
		memset(buf, 0, 128 * 2);
		mixer_callback(globals.pc, (uint8_t *) buf, 128 * 2);
		for (int i = 0; i < 128; i++) {
			buf[i] = buf[i] / 2;
		}
		i2s_channel_write(tx_chan, buf, 128 * 2, &bwritten, portMAX_DELAY);
	}
	i2s_channel_disable(tx_chan);
}

#ifdef USE_BADGE_BSP
static int last_volume = -1;

static void i2s_bsp_task(void *arg)
{
	int core_id = esp_cpu_get_core_id();
	fprintf(stderr, "i2s runs on core %d\n", core_id);

	// Wait for BSP initialization (done by vga_task)
	xEventGroupWaitBits(global_event_group,
			    BIT1,
			    pdFALSE,
			    pdFALSE,
			    portMAX_DELAY);

	// Get I2S handle from BSP
	if (bsp_audio_get_i2s_handle(&tx_chan) != ESP_OK || !tx_chan) {
		fprintf(stderr, "Failed to get I2S handle\n");
		vTaskDelete(NULL);
		return;
	}

	// Configure audio
	bsp_audio_set_rate(44100);
	bsp_audio_set_amplifier(true);

	// Wait for PC to be initialized
	xEventGroupWaitBits(global_event_group,
			    BIT0,
			    pdFALSE,
			    pdFALSE,
			    portMAX_DELAY);

	// Apply initial volume from globals
	int vol = globals.volume;
	if (vol < 0) vol = 0;
	if (vol > 100) vol = 100;
	bsp_audio_set_volume((float)vol);
	last_volume = vol;

	int16_t buf[128];
	i2s_channel_enable(tx_chan);
	for (;;) {
		size_t bwritten;
		memset(buf, 0, 128 * 2);
		mixer_callback(globals.pc, (uint8_t *) buf, 128 * 2);
		for (int i = 0; i < 128; i++) {
			buf[i] = buf[i] / 2;
		}
		i2s_channel_write(tx_chan, buf, 128 * 2, &bwritten, portMAX_DELAY);

		/* Check if volume changed (from OSD or META+arrow) */
		if (globals.volume != last_volume) {
			vol = globals.volume;
			if (vol < 0) vol = 0;
			if (vol > 100) vol = 100;
			bsp_audio_set_volume((float)vol);
			last_volume = vol;
		}
	}
	i2s_channel_disable(tx_chan);
}

void i2s_main()
{
	// Audio is initialized by bsp_device_initialize() in vga_task
	// Just create the task here - it will wait for BSP init
	xTaskCreatePinnedToCore(i2s_bsp_task, "i2s_task", 4096, NULL, 0, NULL, 0);
}
#else
void i2s_main()
{
#ifdef I2S_MCLK
	/* Setp 1: Determine the I2S channel configuration and allocate two channels one by one
	 * The default configuration can be generated by the helper macro,
	 * it only requires the I2S controller id and I2S role
	 * The tx and rx channels here are registered on different I2S controller,
	 * Except ESP32 and ESP32-S2, others allow to register two separate tx & rx channels on a same controller */
	i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
	ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));

	/* Step 2: Setting the configurations of standard mode and initialize each channels one by one
	 * The slot configuration and clock configuration can be generated by the macros
	 * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
	 * They can help to specify the slot and clock configurations for initialization or re-configuring */
	i2s_std_config_t tx_std_cfg = {
		.clk_cfg  = I2S_STD_CLK_DEFAULT_CONFIG(44100),
		.slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
		.gpio_cfg = {
			.mclk = I2S_MCLK,
			.bclk = I2S_BCLK,
			.ws   = I2S_WS,
			.dout = I2S_DOUT,
			.din  = -1,
			.invert_flags = {
				.mclk_inv = false,
				.bclk_inv = false,
				.ws_inv   = false,
			},
		},
	};
	ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &tx_std_cfg));
	xTaskCreatePinnedToCore(i2s_task, "i2s_task", 4096, NULL, 0, NULL, 0);
#endif
}
#endif /* USE_BADGE_BSP */
